config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/gray95/sqaas-openqcd2.0:
      branch: main
      repo: https://github.com/gray95/sqaas-openqcd2.0
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-russet-opossum.sh
        container: qc.acc_surly-viridian-serval
  QC.Doc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-firebrick-wolverine.sh
        container: qc.doc_chummy-sapphire-cockroach
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cerulean-indri.sh
        container: qc.doc_droopy-gold-zebra
      github.com/gray95/sqaas-openqcd2.0 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-salmon-worm.sh
        container: qc.doc_cloudy-coral-flounder
  QC.Lic:
    repos:
      github.com/gray95/sqaas-openqcd2.0 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-chocolate-numbat.sh
        container: qc.lic_snippy-chartreuse-wildebeest
  QC.Ver:
    repos:
      github.com/gray95/sqaas-openqcd2.0 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-blue-crane.sh
        container: qc.ver_gamy-lavender-wombat
timeout: 5400
