config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.8.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/gray95/sqaas-openqcd2.0:
      branch: main
      repo: https://github.com/gray95/sqaas-openqcd2.0
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-platinum-paradise.sh
        container: qc.acc_snappy-plum-dugong
  QC.Doc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-copper-argentino.sh
        container: qc.doc_nippy-cerise-rabbit
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-cornflower-dingo.sh
        container: qc.doc_droopy-ivory-eel
      github.com/gray95/sqaas-openqcd2.0 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-peach-mole.sh
        container: qc.doc_lanky-chestnut-retriever
  QC.Lic:
    repos:
      github.com/gray95/sqaas-openqcd2.0 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-orange-stoat.sh
        container: qc.lic_hazy-red-termite
  QC.Ver:
    repos:
      github.com/gray95/sqaas-openqcd2.0 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-linen-weasel.sh
        container: qc.ver_slaphappy-charcoal-jaguar
timeout: 5400
