config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.8.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/gray95/sqaas-openqcd2.0:
      branch: main
      repo: https://github.com/gray95/sqaas-openqcd2.0
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-sangria-chinook.sh
        container: qc.acc_gamy-cornflower-skunk
  QC.Doc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-tan-hound.sh
        container: qc.doc_scummy-ochre-deer
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-wisteria-squirt.sh
        container: qc.doc_lanky-red-kakapo
      github.com/gray95/sqaas-openqcd2.0 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-brass-ragdoll.sh
        container: qc.doc_pretty-coral-caterpillar
  QC.Lic:
    repos:
      github.com/gray95/sqaas-openqcd2.0 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-maroon-impala.sh
        container: qc.lic_woozy-gold-bison
  QC.Ver:
    repos:
      github.com/gray95/sqaas-openqcd2.0 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-tomato-giraffe.sh
        container: qc.ver_thirsty-cerise-audemer
timeout: 5400
