config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.8.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/gray95/sqaas-openqcd2.0:
      branch: main
      repo: https://github.com/gray95/sqaas-openqcd2.0
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-amber-armadillo.sh
        container: qc.acc_shaky-olive-bordeaux
  QC.Doc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-scarlet-orangutan.sh
        container: qc.doc_trippy-brown-hyrax
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-platinum-rattlesnake.sh
        container: qc.doc_foggy-aquamarine-spaniel
  QC.Lic:
    repos:
      github.com/gray95/sqaas-openqcd2.0 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-ultramarine-ibis.sh
        container: qc.lic_pasty-tangerine-hare
  QC.Ver:
    repos:
      github.com/gray95/sqaas-openqcd2.0 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-wisteria-sloth.sh
        container: qc.ver_scanty-mustard-capybara
timeout: 5400
