config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.8.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/gray95/sqaas-openqcd2.0:
      branch: main
      repo: https://github.com/gray95/sqaas-openqcd2.0
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-aquamarine-lionfish.sh
        container: qc.acc_chewy-ecru-cattle
  QC.Doc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-plum-seahorse.sh
        container: qc.doc_lovely-plum-monkey
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-olive-hamster.sh
        container: qc.doc_foggy-tangerine-moose
      github.com/gray95/sqaas-openqcd2.0 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-orange-blue.sh
        container: qc.doc_cranky-puce-terrier
  QC.Lic:
    repos:
      github.com/gray95/sqaas-openqcd2.0 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-aquamarine-balinese.sh
        container: qc.lic_goopy-saffron-forest
  QC.Ver:
    repos:
      github.com/gray95/sqaas-openqcd2.0 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-harlequin-penguin.sh
        container: qc.ver_fuzzy-periwinkle-harrier
timeout: 5400
