config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.8.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/gray95/sqaas-openqcd2.0:
      branch: main
      repo: https://github.com/gray95/sqaas-openqcd2.0
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-cream-balinese.sh
        container: qc.acc_ugly-vermilion-lemming
  QC.Doc:
    repos:
      github.com/gray95/sqaas-openqcd2.0 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-red-macaw.sh
        container: qc.doc_craggy-eggplant-elephant
      github.com/gray95/sqaas-openqcd2.0 git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-black-chin.sh
        container: qc.doc_wiggy-aquamarine-affenpinscher
      github.com/gray95/sqaas-openqcd2.0 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cobalt-dachsbracke.sh
        container: qc.doc_cranky-chestnut-gharial
  QC.Lic:
    repos:
      github.com/gray95/sqaas-openqcd2.0 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-mauve-caracal.sh
        container: qc.lic_foggy-bistre-beaver
  QC.Ver:
    repos:
      github.com/gray95/sqaas-openqcd2.0 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-pumpkin-bear.sh
        container: qc.ver_randy-rust-mole
timeout: 5400
